server {
    listen 80;
    server_name localhost;

    location /api/ {
        root /var/www/backend/public;
        fastcgi_pass st_php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/backend/public;
        fastcgi_read_timeout 60;
        fastcgi_connect_timeout 60;
    }

    location / {
        proxy_pass http://st_frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    client_max_body_size 32M;
    server_tokens off;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";

    access_log /var/log/nginx/st_access.log;
    error_log  /var/log/nginx/st_error.log;
}
